### PR TITLE
Translation into German

### PR DESCRIPTION
**Pull request by randombyte-developer**
Hello!

This is the translation into German. It is not complete yet as I have questions related to the translation:
1. What are you doing as an instructor? Teacher at school, university or at a company?
2. Max. viewers are the viewers that watched together the stream at the same time? If so, then I would like to clarify this in German(e.g. "Max viewers at same time").
3. Minutes streamed -> Translation of "Duration of whole stream in mins." ok?
4. What to do with strings I don't want to translate like "Dashboard"? Leave it empty or copy the string?

RandomByte

### CODE REVIEW

**Comment by taddeimania** [comment]
Thanks for working on this. My answers to your questions below:
1. What are you doing as an instructor? Teacher at school, university or at a company?
   **I teach at a code school. So not a college, but it's a classroom environment for adults.**
2. Max. viewers are the viewers that watched together the stream at the same time? If so, then I would like to clarify this in German(e.g. "Max viewers at same time").
   **Yes "max viewers at the same time" would be perfect.**
3. Minutes streamed -> Translation of "Duration of whole stream in mins." ok?
   **perfect**
4. What to do with strings I don't want to translate like "Dashboard"? Leave it empty or copy the string?
   **You can leave those strings empty, if the string is empty it will use the default string**

**Comment by randombyte-developer** [comment]
Okay, I am done. When it is live then I will check again whether everything looks nice and is appropriate.

**Comment by taddeimania** [comment]
I deployed it, you can check it out live now.

**Comment by randombyte-developer** [comment]
Some fixes added. But I have to open a new pull request right?

Should I open a new issue for some missing strings like the value of "Trending Up": true and false? There are also other things that aren't in the .po file. I could make a list.

**Comment by taddeimania** [comment]
Yes please open a new PR.

Absolutely open new issues for missing translation strings.  I like to use Issues as a todo list.

**Pull request merged**
